const WORDS = [
  // ── Thiên nhiên ──
  'mặt trời', 'mặt trăng', 'ngôi sao', 'bầu trời', 'gió mát',
  'mưa rơi', 'tuyết rơi', 'sấm chớp', 'cầu vồng', 'mây trắng',
  'biển cả', 'sông dài', 'núi cao', 'đồng bằng', 'thung lũng',
  'hồ nước', 'suối nhỏ', 'vách đá', 'động vật', 'thực vật',
  'hoa lá', 'cây cối', 'rừng xanh', 'cỏ dại', 'lá rơi',
  'hoa nở', 'hoa hồng', 'hoa cúc', 'hoa mai', 'hoa đào',
  'hoa sen', 'hoa lan', 'hoa violet', 'bông tuyết', 'giọt sương',
  'ánh nắng', 'tia sáng', 'bóng tối', 'bầu không', 'luồng khí',
  'nắng vàng', 'mưa phùn', 'gió lạnh', 'sương mù', 'sấm sét',
  'đá cuội', 'cát trắng', 'bụi bay', 'nước sạch', 'lửa cháy',
  'đất liền', 'núi lửa', 'hòn đảo', 'bờ biển', 'cồn cát',
  'đầm lầy', 'ao tù', 'vũng nước', 'mương nước', 'ống nước',
  'khói bụi', 'tro tàn', 'than hồng', 'đá nóng', 'nước đá',
  'tuyết trắng', 'mây đen', 'gió mạnh', 'lốc xoáy', 'bão tố',
  'chớp sáng', 'sấm động', 'trời quang', 'mây vần', 'sương giá',
  // ── Đời sống ──
  'học sinh', 'giáo viên', 'bác sĩ', 'kỹ sư', 'nông dân',
  'thợ máy', 'lái xe', 'ngư dân', 'thợ rèn', 'bếp trưởng',
  'nhà văn', 'nhà thơ', 'họa sĩ', 'nhạc sĩ', 'diễn viên',
  'vận động viên', 'cầu thủ', 'kiện tướng', 'chiến sĩ', 'sĩ quan',
  'cơm tấm', 'phở bò', 'bún chả', 'bánh mì', 'bánh xèo',
  'bánh chưng', 'bánh dày', 'cháo gà', 'mì quảng', 'bún bò',
  'trà đá', 'nước mía', 'sinh tố', 'cà phê', 'sữa chua',
  'kem dừa', 'chè đậu', 'bánh trôi', 'bánh ngọt', 'mứt gừng',
  'đường phố', 'ngõ hẻm', 'phố cổ', 'nhà thờ', 'chùa Một',
  'cầu treo', 'bến phà', 'ga tàu', 'sân bay', 'bến xe',
  'nhà ga', 'cảng biển', 'đèo cao', 'hầm đường', 'ngã tư',
  'ngã năm', 'đường nhựa', 'lối nhỏ', 'vạch kẻ', 'dải phân',
  'xe buýt', 'xe tải', 'xe máy', 'xe đạp', 'xe kéo',
  'tàu hỏa', 'tàu thủy', 'máy bay', 'thuyền buồm', 'canô',
  'đồng hồ', 'máy tính', 'điện thoại', 'máy ảnh', 'tivi',
  'quạt mát', 'đèn pin', 'bình ga', 'nồi cơm', 'bếp gas',
  'tủ lạnh', 'máy giặt', 'máy sấy', 'máy hút', 'bàn là',
  'giường ngủ', 'gối ôm', 'chăn ga', 'tủ quần', 'kệ sách',
  'bàn học', 'ghế ngồi', 'tủ lạnh', 'tủ kính', 'kệ giày',
  'tường nhà', 'mái nhà', 'sân vườn', 'cổng sắt', 'hàng rào',
  'cửa gỗ', 'cửa kính', 'cửa sắt', 'cửa sổ', 'mái hiên',
  'trần nhà', 'sàn nhà', 'cầu thang', 'hành lang', 'phòng ngủ',
  'phòng khách', 'nhà bếp', 'phòng tắm', 'nhà vệ sinh', 'sân thượng',
  'ban công', 'tầng hầm', 'gác mái', 'hiên nhà', 'vòi nước',
  // ── Cơ thể ──
  'đầu óc', 'trán cao', 'mắt sáng', 'tai nghe', 'mũi cao',
  'miệng cười', 'răng trắng', 'lưỡi liếm', 'cổ họng', 'vai rộng',
  'tay chân', 'ngón tay', 'bàn tay', 'cánh tay', 'khuỷu tay',
  'bụng no', 'lưng thẳng', 'đầu gối', 'bắp chân', 'gót chân',
  'xương sống',   'máu nóng', 'tim đập', 'phổi thở', 'gan thải độc',
  'thận khỏe', 'dạ dày', 'ruột già', 'ruột non', 'tuyến tụy',
  'não bộ', 'dây thần', 'tủy sống', 'mạch máu', 'khí quản',
  // ── Cảm xúc ──
  'vui vẻ', 'hạnh phúc', 'tươi cười', 'phấn khởi', 'hào hứng',
  'buồn bã', 'khóc lóc', 'thất vọng', 'chán nản', 'tủi thân',
  'giận dữ', 'nổi nóng', 'tức giận', 'bực mình', 'phẫn nộ',
  'sợ hãi', 'lo lắng', 'bồn chồn', 'hoang mang', 'hoảng loạn',
  'ngạc nhiên', 'bất ngờ', 'kinh ngạc', 'ngỡ ngàng', 'choáng váng',
  'tự hào', 'vinh dự', 'kiêu hãnh', 'thỏa mãn', 'an tâm',
  'nhớ nhung', 'thương nhớ', 'mong nhớ', 'da diết', 'day dứt',
  'yêu thương', 'thương yêu', 'mến mộ', 'tôn kính', 'ngưỡng mộ',
  'thân thiện', 'hòa nhã', 'hiếu khách', 'chân thành', 'thật thà',
  'tự tin', 'quyết đoán', 'can đảm', 'dũng cảm', 'kiên cường',
  // ── Động vật ──
  'con mèo', 'con chó', 'con gà', 'con vịt', 'con ngựa',
  'con bò', 'con heo', 'con dê', 'con cừu', 'con voi',
  'con hổ', 'con sư tử', 'con báo', 'con gấu', 'con sói',
  'con thỏ', 'con nai', 'con hươu', 'con công', 'con quạ',
  'con diều', 'con én', 'con sẻ', 'con vẹt', 'con cú',
  'con rắn', 'con thằn lằn', 'con rùa', 'con ếch', 'con cóc',
  'con tôm', 'con cua', 'con mực', 'con cá', 'con sò',
  'con ong', 'con bướm', 'con kiến', 'con mối', 'con gián',
  'con ruồi', 'con muỗi', 'con ve', 'con dế', 'con sâu',
  'con trùn', 'con đỉa', 'con sam', 'con ngao', 'con hàu',
  'con sá sùng', 'con vẹm', 'con trai', 'con sò điệp', 'con ốc',
  // ── Xianxia / Tu tiên ──
  'linh khí', 'linh mạch', 'linh căn', 'linh dược', 'linh thạch',
  'linh thảo', 'linh thú', 'linh vũ', 'linh đan', 'linh phù',
  'tu luyện', 'tu sĩ', 'đại tu', 'tiểu tu', 'đắc đạo',
  'phi thăng', 'thiên kiếp', 'đại kiếp', 'tiểu kiếp', 'lôi kiếp',
  'pháp bảo', 'pháp khí', 'pháp trận', 'pháp thuật', 'pháp quyết',
  'đan dược', 'đan lô', 'đan phương', 'đan dược', 'đan sư',
  'kiếm khí', 'kiếm thuật', 'kiếm ý', 'kiếm phong', 'kiếm linh',
  'công pháp', 'công lực', 'công pháp', 'đấu pháp', 'ngũ hành',
  'thiên địa', 'nhật nguyệt', 'tinh tú', 'hư không', 'huyền huyễn',
  'bí cảnh', 'tiên cảnh', 'phật cảnh', 'ma cảnh', 'quỷ vực',
  'thần thông', 'thần lực', 'thần kiếm', 'thần đan', 'thần bí',
  'tiên nữ', 'tiên tử', 'tiên đan', 'tiên khí', 'tiên cảnh',
  'ma vương', 'ma kiếm', 'ma pháp', 'ma lực', 'ma quỷ',
  'phật tổ', 'phật pháp', 'phật đan', 'phật tâm', 'phật ý',
  'long tộc', 'rồng vàng', 'rồng bạc', 'rồng đen', 'rồng đỏ',
  'phượng hoàng', 'phượng vũ', 'phượng hoàng', 'tửu điểu', 'kim điểu',
  'tử vi', 'thái âm', 'thái dương', 'thiên không', 'đại địa',
  'cửu thiên', 'tam giới', 'lục đạo', 'ngũ hành', 'bát quái',
  'yên chi', 'son phấn', 'gương sáng', 'đồng bạc', 'vàng son',
  'đấu giá', 'thương hội', 'thánh địa', 'tông môn', 'sơ môn',
  'đệ tử', 'trưởng lão', 'chưởng môn', 'tông chủ', 'đại trưởng',
  'trận pháp', 'phong ấn', 'pháp lý', 'đạo lý', 'đạo pháp',
  'linh mục', 'linh điền', 'linh tuyền', 'linh sơn', 'linh động',
  'kiếm trận', 'đao pháp', 'quyền pháp', 'chưởng pháp', 'cước pháp',
  'thân pháp', 'nhãn pháp', 'thiên nhãn', 'thuật bói', 'bốc phệ',
  'thiên cơ', 'địa lý', 'nhân tướng', 'phong thủy', 'bát tự',
  'đại la', 'kim tiên', 'chân tiên', 'thiên tiên', 'địa tiên',
  'tiên thiên', 'hậu thiên', 'căn cơ', 'phúc duyên', 'nghiệp lực',
  'đoạt thiên', 'cướp cơ', 'lấy số', 'tránh họa', 'diệt tai',
  'yêu tinh', 'đồ yêu', 'đại yêu', 'tiểu yêu', 'yêu vương',
  'quỷ đế', 'đại quỷ', 'tiểu quỷ', 'huyết quỷ', 'hung quỷ',
  'thiên mệnh', 'địa quyết', 'nhân hòa', 'thiên thời', 'địa lợi',
  'bất diệt', 'vô cùng', 'vô hạn', 'vô song', 'vô địch',
  'cửu đỉnh', 'bát bảo', 'lục hợp', 'ngũ hồ', 'tứ hải',
  'tam nguyên', 'nhị khí', 'đại đạo', 'tiểu đạo', 'chánh đạo',
  'tà đạo', 'mê đạo', 'ngã đạo', 'công đạo', 'thiên đạo',
  // ── Thiên nhiên nâng cao ──
  'nắng chói', 'mưa to', 'gió lớn', 'sấm rền', 'chớp giật',
  'sương rơi', 'tuyết tan', 'hơi nước', 'khói xám', 'tro đỏ',
  'đá xanh', 'cát vàng', 'bùn đen', 'sét ngang', 'sấm dồn',
  'mây hồng', 'trăng sáng', 'sao hôm', 'mặt trời', 'bầu trong',
  'núi phủ tuyết', 'sông chảy', 'hồ phản chiếu', 'biển động', 'thác đổ',
  'hang tối', 'động sáng', 'suối reo', 'giếng sâu', 'ao tĩnh',
  'đầm rộng', 'vịnh nhỏ', 'cửa biển', 'sông ngòi', 'mương dẫn',
  'ruộng đồng', 'nông điền', 'cánh đồng', 'vườn cây', 'rừng rậm',
  'chùm cây', 'cây cổ', 'thân cây', 'gốc cây', 'ngọn cây',
  'lá xanh', 'hoa đỏ', 'quả chín', 'hạt giống', 'mầm non',
  'rễ cây', 'cành cây', 'tán lá', 'vỏ cây', 'gỗ quý',
  'tre già', 'măng non', 'cỏ úa', 'lá vàng', 'hoa tím',
  'nấm mọc', 'nấm độc', 'nấm linh', 'nấm lim', 'nấm lim',
  'đá ong', 'đá vôi', 'đá hoa', 'đá granit', 'đá cẩm thạch',
  // ── Đời sống nâng cao ──
  'áo dài', 'áo sơ mi', 'quần jean', 'váy đầm', 'áo len',
  'giày tây', 'dép lê', 'mũ len', 'khăn quàng', 'găng tay',
  'túi xách', 'ví tiền', 'đồng hồ', 'mắt kính', 'nón lá',
  'nón bảo', 'áo mưa', 'áo khoác', 'áo vest', 'áo choàng',
  'mì vằn thắn', 'bánh canh', 'bánh bèo', 'bánh bột', 'bánh khoai',
  'bánh rán', 'bánh mì', 'bánh crepe', 'bánh flan', 'bánh pudding',
  'trứng gà', 'trứng vịt', 'trứng cút', 'trứng lộn', 'trứng chiên',
  'rau muống', 'rau cải', 'rau dền', 'rau thơm', 'rau lang',
  'cà rốt', 'cà chua', 'cà tím', 'khoai lang', 'khoai tây',
  'hành tây', 'tỏi tây', 'gừng tươi', 'ớt đỏ', 'tiêu đen',
  'muối trắng', 'đường phèn', 'nước mắm', 'dầu ăn', 'giấm gạo',
  'đậu hũ', 'đậu nành', 'đậu xanh', 'đậu đỏ', 'đậu đen',
  'thịt bò', 'thịt gà', 'thịt heo', 'thịt cừu', 'thịt dê',
  'cá hồi', 'cá ngừ', 'cá cơm', 'cá lóc', 'cá trê',
  'tôm sú', 'tôm thẻ', 'tôm hùm', 'tôm đất', 'tôm tươi',
  'ghẹ biển', 'cua biển', 'sò huyết', 'ngao trắng', 'hàu sữa',
  'mực ống', 'mực nang', 'mực lá', 'bạch tuộc', 'mực khô',
  // ── Gia đình ──
  'ông bà', 'cha mẹ', 'anh chị', 'em út', 'cháu nhỏ',
  'chú bác', 'cô dì', 'chú ruột', 'cô ruột', 'dì ruột',
  'bố mẹ', 'ông cố', 'bà cố', 'cháu nội', 'cháu ngoại',
  'con trai', 'con gái', 'con út', 'con giữa', 'con đầu',
  'vợ chồng', 'bạn đời', 'người yêu', 'đối tác', 'đồng nghiệp',
  // ── Giáo dục ──
  'sách vở', 'vở viết', 'bút chì', 'bút mực', 'cây thước',
  'cặp sách', 'balo học', 'bảng đen', 'phấn trắng', 'bút đỏ',
  'điểm số', 'điểm mười', 'điểm cao', 'thi cử', 'kỳ thi',
  'đề thi', 'bài thi', 'câu hỏi', 'đáp án', 'bài giải',
  'giáo trình', 'bài giảng', 'thuyết trình', 'bài tập', 'đồ án',
  'thạc sĩ', 'tiến sĩ', 'cử nhân', 'nghiên cứu', 'luận văn',
  // ── Thời gian ──
  'buổi sáng', 'buổi trưa', 'buổi chiều', 'buổi tối', 'nửa đêm',
  'tháng giêng', 'tháng hai', 'tháng ba', 'tháng tư', 'tháng năm',
  'mùa xuân', 'mùa hè', 'mùa thu', 'mùa đông', 'năm mới',
  'ngày sinh', 'ngày lễ', 'ngày nghỉ', 'ngày thường', 'ngày cuối',
  'giờ phút', 'giây khắc', 'khoảnh khắc', 'thời gian', 'thời điểm',
  'sớm mai', 'chiều tà', 'hoàng hôn', 'bình minh', 'nắng sớm',
  // ── Số đếm ──
  'một hai', 'ba bốn', 'năm sáu', 'bảy tám', 'chín mười',
  'một nửa', 'một phần', 'hai phần', 'ba phần', 'một phần tư',
  // ── Màu sắc ──
  'màu đỏ', 'màu xanh', 'màu vàng', 'màu trắng', 'màu đen',
  'màu hồng', 'màu tím', 'màu cam', 'màu nâu', 'màu xám',
  'màu be', 'màu kem', 'màu đồng', 'màu bạc', 'màu vàng',
  // ── Hành động ──
  'ăn cơm', 'uống nước', 'đi bộ', 'chạy bộ', 'bơi lội',
  'nhảy dây', 'đạp xe', 'lái xe', 'nấu ăn', 'rửa chén',
  'quét nhà', 'lau nhà', 'giặt đồ', 'phơi đồ', 'ủi đồ',
  'may vá', 'đan len', 'thêu thùa', 'vẽ tranh', 'chụp ảnh',
  'nghe nhạc', 'xem phim', 'đọc sách', 'viết thư', 'gọi điện',
  'nhắn tin', 'chat chit', 'lướt web', 'chơi game', 'điều khiển',
  'hát karaoke', 'nhảy múa', 'kể chuyện', 'trò chuyện', 'thảo luận',
  'học bài', 'ôn bài', 'thi cử', 'làm bài', 'trả bài',
  'đi chợ', 'mua sắm', 'bán hàng', 'bày bán', 'trưng bày',
  'nghỉ ngơi', 'đi ngủ', 'thức dậy', 'tắm rửa', 'chải đầu',
  'đánh răng', 'súc miệng', 'rửa mặt', 'chăm sóc', 'làm đẹp',
  'tập thể', 'yoga', 'thiền định', 'đi bộ', 'chạy bộ',
  'leo núi', 'cắm trại', 'dã ngoại', 'câu cá', 'săn bắn',
  // ── Đồ vật ──
  'bút thước', 'giấy tờ', 'hồ sơ', 'bản đồ', 'la bàn',
  'đồng hồ', 'máy tính', 'máy in', 'máy photocopy', 'máy scan',
  'ổ khóa', 'chìa khóa', 'két sắt', 'tủ sắt', 'kho tiền',
  'giỏ quà', 'hộp quà', 'nơ hồng', 'ruy băng', 'giấy gói',
  'nến thơm', 'hoa khô', 'tranh vẽ', 'khung ảnh', 'đồng hồ',
  'gương soi', 'bàn chải', 'kéo cắt', 'dao cắt', 'búa đập',
  'đinh vít', 'tua vít', 'cờ lê', 'mỏ lết', 'kìm cắt',
  'xe container', 'xe ben', 'xe cứu hỏa', 'xe cấp cứu', 'xe cảnh sát',
  'tàu chiến', 'tàu ngầm', 'tàu vũ trụ', 'máy bay phản lực', 'máy bay trực thăng',
  // ── Tự nhiên & Thời tiết ──
  'gió heo', 'mưa bụi', 'nắng gắt', 'sương giá', 'sấm rền',
  'mây đen', 'chớp sáng', 'lốc xoáy', 'bão mạnh', 'lũ quét',
  'hạn hán', 'độ ẩm', 'nhiệt độ', 'khí hậu', 'thời tiết',
  'bão tố', 'mưa đá', 'tuyết rơi', 'sương sớm', 'sương đêm',
  // ── Thức uống ──
  'trà xanh', 'trà đen', 'trà sữa', 'trà nhài', 'trà Atisô',
  'nước chanh', 'nước cam', 'nước dừa', 'nước mía', 'nước lọc',
  'cà phê đen', 'cà phê sữa', 'cappuccino', 'latte', 'mocha',
  'sinh tố', 'nước ép', 'trái cây', 'đá xay', 'kem ly',
  'soda', 'nước tăng lực', 'bia lạnh', 'rượu vang', 'rượu nếp',
  // ── Sức khỏe ──
  'khám bệnh', 'tiêm phòng', 'uống thuốc', 'bệnh viện', 'nhà thuốc',
  'bác sĩ khám', 'y tá chăm', 'đo huyết', 'xét nghiệm', 'siêu âm',
  'chụp X', 'phẫu thuật', 'hồi phục', 'điều trị', 'chăm sóc',
  'dinh dưỡng', 'vitamin', 'thực phẩm', 'bổ sung', 'thuốc bổ',
  // ── Du lịch ──
  'vé máy bay', 'khách sạn', 'resort', 'homestay', 'nhà trọ',
  'hành lý', 'vali lớn', 'balo nhỏ', 'giỏ xách', 'túi du lịch',
  'địa điểm', 'danh lam', 'thắng cảnh', 'di tích', 'lịch sử',
  'văn hóa', 'ẩm thực', 'mua sắm', 'giải trí', 'nghỉ dưỡng',
  // ── Khoa học ──
  'vũ trụ', 'hành tinh', 'mặt trời', 'ngôi sao', 'thiên hà',
  'vật lý', 'hóa học', 'sinh học', 'toán học', 'thiên văn học',
  'nguyên tử', 'phân tử', 'electron', 'proton', 'neutron',
  'năng lượng', 'điện năng', 'quang hợp', 'đại dương', 'khí quyển',
  // ── Nghệ thuật ──
  'âm nhạc', 'hội họa', 'điêu khắc', 'thơ ca', 'văn chương',
  'sân khấu', 'điện ảnh', 'nhiếp ảnh', 'múa rối', 'ca múa',
  'tranh lụa', 'tranh sơn', 'tranh vẽ', 'phác họa', 'màu nước',
  'đàn piano', 'đàn guitar', 'đàn organ', 'sáo trúc', 'đàn tranh',
  // ── Địa lý ──
  'châu Á', 'châu Âu', 'châu Phi', 'châu Mỹ', 'châu Đại',
  'đại dương', 'lục địa', 'hải dương', 'biển Đông', 'vịnh Bắc',
  'sông Hồng', 'sông Mê', 'sông Cửu', 'sông Đồng', 'hồ Gươm',
  'núi Bà', 'núi Fansipan', 'đà Lạt', 'Phú Quốc', 'Hạ Long',
  'Hội An', 'Huế cổ', 'Sapa', 'Nha Trang', 'Đà Nẵng',
  // ── Tôn giáo ──
  'đạo Phật', 'đạo Chúa', 'đạo Hồi', 'đạo Thiên', 'đạo Hindu',
  'thiền định', 'cầu nguyện', 'giác ngộ', 'phương trời', 'niết bàn',
  'từ bi', 'hỷ xả', 'bát chánh', 'tứ diệu', 'lục độ',
  // ── Kinh tế ──
  'thu nhập', 'chi tiêu', 'tiết kiệm', 'đầu tư', 'kinh doanh',
  'lợi nhuận', 'doanh thu', 'thuế phí', 'lạm phát', 'tài chính',
  'ngân hàng', 'chứng khoán', 'bất động', 'vàng bạc', 'tiền tệ',
  // ── Luật pháp ──
  'pháp luật', 'tòa án', 'thẩm phán', 'luật sư', 'công tố',
  'bản án', 'tù tội', 'phạt tiền', 'cảnh cáo', 'bồi thường',
  // ── Xã hội ──
  'cộng đồng', 'xã hội', 'dân cư', 'đô thị', 'nông thôn',
  'giáo dục', 'y tế', 'văn hóa', 'thể thao', 'giải trí',
  'báo chí', 'truyền hình', 'internet', 'mạng xã', 'điện tử',
  // ── Thể thao ──
  'bóng đá', 'bóng rổ', 'bóng chuyền', 'bóng bàn', 'bóng bầu',
  'cầu lông', 'quần vợt', 'golf', 'đua xe', 'bơi lội',
  'điền kinh', 'vật lộn', 'judo', 'karate', 'taekwondo',
  'boxing', 'kickboxing', 'muay thai', 'cử tạ', 'gym',
  'yoga', 'pilates', 'aerobic', 'zumba', 'giãn cơ',
  // ── Công nghệ ──
  'phần mềm', 'phần cứng', 'máy chủ', 'mạng máy', 'công nghệ',
  'trí tuệ', 'nhân tạo', 'robot', 'AI', 'blockchain',
  'điện toán', 'đám mây', 'an ninh', 'mạng lưới', 'dữ liệu',
  'thuật toán', 'ngôn ngữ', 'lập trình', 'ứng dụng', 'website',
  // ── Xianxia bổ sung ──
  'kiếm khí', 'đao khí', 'quyền cước', 'thân pháp', 'nhãn thuật',
  'thiên cơ', 'địa lý', 'nhân hòa', 'đại đạo', 'tiểu đạo',
  'cửu thiên', 'thập địa', 'bát phương', 'lục hợp', 'tứ cực',
  'ngũ hành', 'bát quái', 'càn khôn', 'thái cực', 'vô cực',
  'hư không', 'niết bàn', 'giác ngộ', 'phật tâm', 'đạo tâm',
  'ma tâm', 'quỷ nhãn', 'thiên nhãn', 'pháp nhãn', 'huệ nhãn',
  'thần lực', 'phật lực', 'ma lực', 'yêu lực', 'quỷ lực',
  'tiên khí', 'phật khí', 'ma khí', 'yêu khí', 'quỷ khí',
  'đại đan', 'tiểu đan', 'cấp đan', 'đan dược', 'đan phương',
  'linh dược', 'thảo dược', 'cổ dược', 'độc dược', 'bổ dược',
  'kiếm trận', 'pháp trận', 'bố trận', 'phá trận', 'trận đồ',
  'phong ấn', 'giải ấn', 'phá ấn', 'khóa ấn', 'mở ấn',
  'thiên kiếp', 'đại kiếp', 'tiểu kiếp', 'lôi kiếp', 'hỏa kiếp',
  'phi thăng', 'đăng tiên', 'bắc thiên', 'nam thiên', 'đông thiên',
  'tây thiên', 'trung thiên', 'thượng thiên', 'hạ thiên', 'trung thiên',
  'tiên giới', 'phật giới', 'ma giới', 'quỷ giới', 'yêu giới',
  'long cung', 'phượng sào', 'huyền quy', 'tửu điểu', 'kỳ lân',
  'thiên long', 'địa long', 'hải long', 'cơ long', 'hỏa long',
  'băng long', 'lôi long', 'phong long', 'thổ long', 'mộc long',
  'kim long', 'thủy long', 'huyết long', 'cổ long', 'thần long',
];

export const VIETNAMESE_WORDS: Set<string> = new Set(WORDS.map(w => w.trim().toLowerCase()));

export function isValidVietnameseWord(word: string): boolean {
  return VIETNAMESE_WORDS.has(word.trim().toLowerCase());
}
